### ISSUE TITLE
Support for cudafortran

### ISSUE THREAD

**Issue by oponkork** [stadelmanma/tree-sitter-fortran#44]
Hi,

Thanks for your work on the grammar. I would like to contribute to it, mostly to support cudafortran. I was wondering if you will accept pull requests for the same or should I create a new repository which extends the tree-sitter-fortran grammar?

**Comment by stadelmanma** [comment]
Hi @openkork! Glad to hear you are interested in the parser, it does have a few bugs I haven't figured out and some features I didn't have a chance to implement most (maybe all?) of which are documented here. I would wager we could add the cudafortran straight to this repo. What all rules need added?

**Comment by oponkork** [comment]
Hi @stadelmanma Thanks for the reply.
I have created a draft pull request, with some of the changes I have made.
I have just started playing with tree-sitter, so please bear with me.
:)

**Comment by stadelmanma** [comment]
@oponkork great! Test files are under `test/corpus` since this is a somewhat separate subset of the language I would recommend adding them to their own file `test/corpus/cudafortran.txt`. If you haven't found them yet the tree-sitter documentation is now pretty good. https://tree-sitter.github.io/tree-sitter/

**Comment by stadelmanma** [comment]
@oponkork I have merged the first PR, everything looked great. Good work!

**Comment by oponkork** [comment]
@stadelmanma Thanks a lot. Will add some more rules in few days.

**Comment by oponkork** [comment]
Closing as cudafortran is almost fully supported now.
