### ISSUE TITLE
Support for intrinsic fortran functions

### ISSUE THREAD

**Issue by oponkork** [stadelmanma/tree-sitter-fortran#46]
I was looking for grammar rules for intrinsic fortran procedures ([listed here](https://gcc.gnu.org/onlinedocs/gfortran/Intrinsic-Procedures.html#Intrinsic-Procedures)), but didn't find any. Should we add it?

**Comment by stadelmanma** [comment]
Tree-sitter parsers are more targeted towards syntax and code constructs, so all those intrinsic procedures as well as user defined functions fall under the general "call statement" rule. (See https://github.com/stadelmanma/tree-sitter-fortran/blob/68786b2bee892137c3b735df836eabbe25361745/grammar.js#L878).
