### ISSUE TITLE
Array constructors are not parsed

### ISSUE THREAD

**Issue by ghost** [stadelmanma/tree-sitter-fortran#47]
Currently, [array constructs](https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-developer-guide-and-reference/top/language-reference/data-types-constants-and-variables/variables-1/arrays/array-constructors.html) are not parsed. We should add support for them. Simple scalar expressions like
```fortran
integer :: array(3)
array = (/1, 2, 3 /)
array = [4, 5, 6]
```
are easy to implement. But array expressions and implied-do loops are also allowed, which will require #3 to be implemented first.

**Comment by oponkork** [comment]
@stadelmanma 

I see you have already mentioned array constructs in #3

**Comment by stadelmanma** [comment]
Oops, I thought the mentioned issue was regarding array constructors and I closed before I looked.

**Comment by stadelmanma** [comment]
@oponkork among some other fixes I've implemented I did add support for array literals using the square brackets. Implied do loops are still untouched though.

**Comment by oponkork** [comment]
I will try to get the implied do loops working.

**Comment by stadelmanma** [comment]
Hey @oponkork I was looking through my old branch for this and had a thought, I think I got something working. Checkout my changes in https://github.com/stadelmanma/tree-sitter-fortran/tree/support-implied-do-loops and see what you think. Maybe you have a better solution than just adding a conflict rule.
