### ISSUE TITLE
Parser error when assigning to a keyword

### ISSUE THREAD

**Issue by stadelmanma** [stadelmanma/tree-sitter-fortran#53]
Fortran allows any variable to be assigned to and we get an error when that occurs with a keyword. See the pared down snippet from the [Fire Models FDS code base](https://github.com/firemodels/fds) (file: pois.f90, line 6115). 

```fortran
SUBROUTINE FSH08S(AN,CN,B,COEF,T)

IF = 2**KAPPA

end subroutine
```

**Comment by ZedThree** [comment]
This also seems to apply to identifiers like `double` which form part of white-spaced keywords like `double precision`:

```fortran
elemental integer function double(x)
  integer, intent(in) :: x
  double = 2 * x
end function double
```
