### ISSUE TITLE
Parse error when whitespace or comment follows line continuation

### ISSUE THREAD

**Issue by ZedThree** [stadelmanma/tree-sitter-fortran#73]
If there is any whitespace or comments following a line continuation, then there's an error:

```fortran
program test
    write(*, "('Testing line continuation')", &
       &  advance='no', &   ! comment
          iostat=istat)
end program
```

Result:

```diff
- Actual
+ Expected

    (translation_unit
      (program
        (program_statement
          (name))
        (write_statement
          (unit_identifier)
          (format_identifier
            (string_literal))
          (keyword_argument
            (identifier)
            (string_literal))
-          (ERROR
-            (UNEXPECTED '&')
-            (comment)))
+          (keyword_argument
+           (identifier)
+           (identifier)))
        (end_program_statement)))
```

I guess this needs to be fixed in `scanner.cc`, but I don't quite understand how to fix it. I thought the following would be sufficient, at least when it's just whitespace, but it gives `(UNEXPECTED '&')`:

```diff
@@ -173,6 +173,10 @@ struct Scanner {
         }
         advance(lexer);
 
+        while (iswspace(lexer->lookahead)) {
+          advance(lexer);
+        }
+
         // Consume end of line characters, we allow '\n', '\r\n' and
         // '\r' to cover unix, MSDOS and old style Macintosh
         if (lexer->lookahead == '\r') {
```

**Comment by stadelmanma** [comment]
@ZedThree I'm not sure exactly how to fix it either, it's been so long since I've been deep into the logic of how tree-sitter works I don't remember how scanner.cc factors in with the regular parsing flow (i.e. does it check the grammar.js rules when `advance` is called or not until it returns).

**Comment by ZedThree** [comment]
Here's another edge-case for line continuations from my Fortran teaching course:

```fortran
    print*, "You picked a number between twenty and fifty,&
            & excluding forty-two"
```

`&` can appear inside string literals, in which case I'm reasonably certain it _must_ appear as the first character (not column) on the next line.

I've read that tree-sitter doesn't aim for "type-II correctness", which I interpret to mean: "tree-sitter should be able to parse all valid programs, but not necessarily reject all invalid programs".
So that might give us some latitude to not worry so much about missing `&` on the second line
