### ISSUE TITLE
Parse variable declarations with dimension size differently

### ISSUE THREAD

**Issue by ZedThree** [stadelmanma/tree-sitter-fortran#86]
Currently variable declarations like the following:

```fortran
INTEGER :: l(*)
```

get parsed like as:

```lisp
    (variable_declaration (intrinsic_type)
      (call_expression (identifier) (argument_list (assumed_size))))
```

I'm not keen on the `call_expression` there as I think we should be able to always distinguish between declarations and function calls in this context.

A small tweak to the grammar can give:

```lisp
    (variable_declaration (intrinsic_type)
      (identifier) (size (argument_list (assumed_size))))
```

I'm not completely convinced by this -- maybe it would be better to have another node? And/or drop the `argument_list` node?

```lisp
    (variable_declaration (intrinsic_type)
      (variable      
        (identifier) 
        (size (assumed_size))))
```

**Comment by stadelmanma** [comment]
I think dropping the call expression makes sense based on your reasoning. I’m less concerned about argument_list since it’s sort of an accurate description but your final example output seems the cleanest. I don’t think we need another node?
