### ISSUE TITLE
Pypi Package Support

### ISSUE THREAD

**Issue by vintriguna** [stadelmanma/tree-sitter-fortran#96]
Hi,
Would there be any way to add Pypi package support for Fortran tree sitter? Thank you.

**Comment by ZedThree** [comment]
Hmmm, I was going to say that you can use https://github.com/grantjenks/py-tree-sitter-languages, but it looks like that's now unmaintained and broken for the latest `tree-sitter` version.

I guess that means this needs a python package. I'll have a look at that when I can

**Comment by stadelmanma** [comment]
I believe I have a PYPI account that I could publish with, does this require any code changes?

**Comment by stadelmanma** [comment]
@ZedThree  tried your route initially and it failed with PYPI errors, so I copied what they did in tree-sitter-c and got closer but still no dice. I'll try to circle back around in a few days. I did manage to get it on crates.io with ease but that doesn't help us here.

**Comment by stadelmanma** [comment]
Sorry for the delay on this, but I think it's good to go now, https://pypi.org/project/tree-sitter-fortran/.
